# Generated by Django 5.0.4 on 2024-04-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='patientname',
            new_name='pname',
        ),
    ]
