# Generated by Django 5.0.4 on 2024-04-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0002_rename_patientname_appoinment_pname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='appoinmentdate',
            new_name='Adate',
        ),
        migrations.RenameField(
            model_name='appoinment',
            old_name='department',
            new_name='Dname',
        ),
        migrations.RenameField(
            model_name='appoinment',
            old_name='doctorname',
            new_name='docname',
        ),
        migrations.RenameField(
            model_name='appoinment',
            old_name='sympotoms',
            new_name='symptoms',
        ),
    ]
