# Generated by Django 5.0.4 on 2024-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0003_rename_appoinmentdate_appoinment_adate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dnumber', models.CharField(max_length=200)),
                ('Dname', models.CharField(max_length=300)),
                ('docname', models.CharField(max_length=200)),
            ],
        ),
    ]
