# Generated by Django 5.0.4 on 2024-04-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0005_patientregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='password1',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
