# Generated by Django 5.0.4 on 2024-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0006_patientregistration_password1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=250)),
                ('spln', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=250)),
                ('docdob', models.CharField(max_length=300)),
                ('docaddress', models.CharField(max_length=350)),
                ('doccontact', models.CharField(max_length=300)),
                ('docemail', models.CharField(max_length=400)),
                ('docworkD', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=400)),
                ('password1', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
